# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class SideGrip(QtWidgets.QWidget):

    def __init__(self, parent, edge):
        QtWidgets.QWidget.__init__(self, parent)

        #self.setStyleSheet("border : 1px solid #000000;")

        self.WidgetSideGrip = QtWidgets.QWidget(self)
        self.WidgetSideGrip.setObjectName('WidgetSideGrip')
        self.WidgetSideGrip.setStyleSheet('''
            QWidget#WidgetSideGrip {
                background: #D37242;
                border-radius: 20px;
                border: 12px solid #D37242;                   
            }
        ''')

        self.BoxLayoutSideGrip = QtWidgets.QVBoxLayout(self)
        self.BoxLayoutSideGrip.setContentsMargins(0, 0, 0, 0)
        self.BoxLayoutSideGrip.addWidget(self.WidgetSideGrip)

        if edge == QtCore.Qt.LeftEdge:
            self.setCursor(QtCore.Qt.SizeHorCursor)
            self.resizeFunction = self.resizeLeft

        elif edge == QtCore.Qt.TopEdge:
            self.setCursor(QtCore.Qt.SizeVerCursor)
            self.resizeFunction = self.resizeTop

        elif edge == QtCore.Qt.RightEdge:
            self.setCursor(QtCore.Qt.SizeHorCursor)
            self.resizeFunction = self.resizeRight

        else:
            self.setCursor(QtCore.Qt.SizeVerCursor)
            self.resizeFunction = self.resizeBottom

        self.mousePos = None



    def resizeLeft(self, delta):
        window = self.window()
        width = max(window.minimumWidth(), window.width() - delta.x())
        geo = window.geometry()
        geo.setLeft(geo.right() - width)
        window.setGeometry(geo)

    def resizeTop(self, delta):
        window = self.window()
        height = max(window.minimumHeight(), window.height() - delta.y())
        geo = window.geometry()
        geo.setTop(geo.bottom() - height)
        window.setGeometry(geo)

    def resizeRight(self, delta):
        window = self.window()
        width = max(window.minimumWidth(), window.width() + delta.x())
        window.resize(width, window.height())

    def resizeBottom(self, delta):
        window = self.window()
        height = max(window.minimumHeight(), window.height() + delta.y())
        window.resize(window.width(), height)

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.mousePos = event.pos()

    def mouseMoveEvent(self, event):
        if self.mousePos is not None:
            delta = event.pos() - self.mousePos
            self.resizeFunction(delta)

    def mouseReleaseEvent(self, event):
        self.mousePos = None



class MainWindowView(QtWidgets.QMainWindow):
    _gripSize = 1

    def __init__(self, Controller):
        super().__init__()

        self.Controller = Controller

        self.setWindowFlags(Qt.CustomizeWindowHint | Qt.FramelessWindowHint)
        self.sideGrips = [
            SideGrip(self, QtCore.Qt.LeftEdge), 
            SideGrip(self, QtCore.Qt.TopEdge), 
            SideGrip(self, QtCore.Qt.RightEdge), 
            SideGrip(self, QtCore.Qt.BottomEdge), 
        ]
        self.cornerGrips = [QtWidgets.QSizeGrip(self) for i in range(4)]

    @property
    def gripSize(self):
        return self._gripSize

    def setGripSize(self, size):
        if size == self._gripSize:
            return
        self._gripSize = max(2, size)
        self.updateGrips()

    def updateGrips(self):
        self.setContentsMargins(*[self.gripSize] * 4)

        outRect = self.rect()
        inRect = outRect.adjusted(self.gripSize, self.gripSize,
            -self.gripSize, -self.gripSize)

        # top left
        self.cornerGrips[0].setGeometry(
            QtCore.QRect(outRect.topLeft(), inRect.topLeft()))

        # top right
        self.cornerGrips[1].setGeometry(
            QtCore.QRect(outRect.topRight(), inRect.topRight()).normalized())

        # bottom right
        self.cornerGrips[2].setGeometry(
            QtCore.QRect(inRect.bottomRight(), outRect.bottomRight()))

        # bottom left
        self.cornerGrips[3].setGeometry(
            QtCore.QRect(outRect.bottomLeft(), inRect.bottomLeft()).normalized())

        # left edge
        self.sideGrips[0].setGeometry(
            0, inRect.top(), self.gripSize, inRect.height())

        # top edge
        self.sideGrips[1].setGeometry(
            inRect.left(), 0, inRect.width(), self.gripSize)

        # right edge
        self.sideGrips[2].setGeometry(
            inRect.left() + inRect.width(), 
            inRect.top(), self.gripSize, inRect.height())

        # bottom edge
        self.sideGrips[3].setGeometry(
            self.gripSize, inRect.top() + inRect.height(), 
            inRect.width(), self.gripSize)

    def closeEvent(self, event):
        self.destroy()

    def resizeEvent(self, event):
        QtWidgets.QMainWindow.resizeEvent(self, event)
        self.updateGrips()

    def mousePressEvent(self, event):
        if event.buttons() == Qt.LeftButton:
            self.m_drag = True
            self.m_DragPosition = event.globalPos()-self.pos()
            event.accept()

    def mouseMoveEvent(self, event):
        try:
            if event.buttons() and Qt.LeftButton:
                self.move(event.globalPos()-self.m_DragPosition)
                event.accept()
        except AttributeError:
            pass

    def mouseReleaseEvent(self, event):
        self.m_drag = False

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Escape:
            qApp.quit()

        elif event.key() == QtCore.Qt.Key_F1:
            return self.stackedWidgetModule.setCurrentWidget(self.homeModule)

        elif event.key() == QtCore.Qt.Key_F2:
            return self.stackedWidgetModule.setCurrentWidget(self.analysisModule)

        elif event.key() == QtCore.Qt.Key_F3:
            return self.stackedWidgetModule.setCurrentWidget(self.executionModule)

        elif event.key() == QtCore.Qt.Key_F4:
            return self.stackedWidgetModule.setCurrentWidget(self.propertiesModule)

        elif event.key() == QtCore.Qt.Key_F5:
            self.Controller.request_data()
            return self.stackedWidgetModule.setCurrentWidget(self.analysisModule)

        else:
            super().keyPressEvent(event)

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.setEnabled(True)
        self.resize(950, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(900, 0))
        self.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtWidgets.QWidget(self)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frameMenuPanel = QtWidgets.QFrame(self.centralWidget)
        self.frameMenuPanel.setMinimumSize(QtCore.QSize(46, 0))
        self.frameMenuPanel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frameMenuPanel.setStyleSheet("QFrame {\n"
"    background : #333333;\n"
"}")
        self.frameMenuPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenuPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMenuPanel.setLineWidth(0)
        self.frameMenuPanel.setObjectName("frameMenuPanel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameMenuPanel)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameMenuPanelPushButton = QtWidgets.QFrame(self.frameMenuPanel)
        self.frameMenuPanelPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.frameMenuPanelPushButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenuPanelPushButton.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMenuPanelPushButton.setLineWidth(0)
        self.frameMenuPanelPushButton.setObjectName("frameMenuPanelPushButton")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameMenuPanelPushButton)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.pushButtonLeaveSession = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonLeaveSession.setStyleSheet("QPushButton{\n"
"    background-color: #333333;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #555555;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-exit-to-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLeaveSession.setIcon(icon)
        self.pushButtonLeaveSession.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonLeaveSession.setObjectName("pushButtonLeaveSession")
        self.gridLayout_2.addWidget(self.pushButtonLeaveSession, 6, 0, 1, 1)
        self.pushButtonAnalysisModule = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonAnalysisModule.setStyleSheet("QPushButton{\n"
"    background-color: #333333;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #555555;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-object-ungroup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAnalysisModule.setIcon(icon1)
        self.pushButtonAnalysisModule.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAnalysisModule.setObjectName("pushButtonAnalysisModule")
        self.gridLayout_2.addWidget(self.pushButtonAnalysisModule, 1, 0, 1, 1)
        self.pushButtonPropertiesModule = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonPropertiesModule.setStyleSheet("QPushButton{\n"
"    background-color: #333333;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #555555;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPropertiesModule.setIcon(icon2)
        self.pushButtonPropertiesModule.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonPropertiesModule.setObjectName("pushButtonPropertiesModule")
        self.gridLayout_2.addWidget(self.pushButtonPropertiesModule, 3, 0, 1, 1)
        self.pushButtonHomeModule = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonHomeModule.setStyleSheet("QPushButton{\n"
"    background-color: #333333;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #555555;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHomeModule.setIcon(icon3)
        self.pushButtonHomeModule.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonHomeModule.setObjectName("pushButtonHomeModule")
        self.gridLayout_2.addWidget(self.pushButtonHomeModule, 0, 0, 1, 1)
        self.pushButtonExecutionModule = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonExecutionModule.setStyleSheet("QPushButton{\n"
"    background-color: #333333;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #555555;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-mug-tea.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExecutionModule.setIcon(icon4)
        self.pushButtonExecutionModule.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonExecutionModule.setObjectName("pushButtonExecutionModule")
        self.gridLayout_2.addWidget(self.pushButtonExecutionModule, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.pushButtonOpenWebsite = QtWidgets.QPushButton(self.frameMenuPanelPushButton)
        self.pushButtonOpenWebsite.setStyleSheet("QPushButton{\n"
"    background-color: #21CD63;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #6B973F;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOpenWebsite.setIcon(icon5)
        self.pushButtonOpenWebsite.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonOpenWebsite.setObjectName("pushButtonOpenWebsite")
        self.gridLayout_2.addWidget(self.pushButtonOpenWebsite, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frameMenuPanelPushButton, 2, 0, 1, 1)
        self.pushButtonSwipeMenuPanel = QtWidgets.QPushButton(self.frameMenuPanel)
        self.pushButtonSwipeMenuPanel.setStyleSheet("QPushButton{\n"
"    background-color: #D37242;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #AD5B32;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"}\n"
"")
        self.pushButtonSwipeMenuPanel.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSwipeMenuPanel.setIcon(icon6)
        self.pushButtonSwipeMenuPanel.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSwipeMenuPanel.setObjectName("pushButtonSwipeMenuPanel")
        self.gridLayout_3.addWidget(self.pushButtonSwipeMenuPanel, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameMenuPanel, 1, 0, 1, 1)
        self.frameContainer = QtWidgets.QFrame(self.centralWidget)
        self.frameContainer.setStyleSheet("QFrame {\n"
"    background : #FFFFFF;\n"
"}")
        self.frameContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameContainer.setLineWidth(0)
        self.frameContainer.setObjectName("frameContainer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frameContainer)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidgetModule = QtWidgets.QStackedWidget(self.frameContainer)
        self.stackedWidgetModule.setMinimumSize(QtCore.QSize(0, 50))
        self.stackedWidgetModule.setLineWidth(0)
        self.stackedWidgetModule.setObjectName("stackedWidgetModule")
        self.homeModule = QtWidgets.QWidget()
        self.homeModule.setStyleSheet("QWidget {\n"
"    background-color : #F0F0F0;\n"
"}")
        self.homeModule.setObjectName("homeModule")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.homeModule)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelHomeModule = QtWidgets.QLabel(self.homeModule)
        self.labelHomeModule.setMinimumSize(QtCore.QSize(0, 50))
        self.labelHomeModule.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelHomeModule.setBaseSize(QtCore.QSize(0, 50))
        self.labelHomeModule.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelHomeModule.setObjectName("labelHomeModule")
        self.gridLayout_7.addWidget(self.labelHomeModule, 0, 0, 1, 1)
        self.frameHomeContent = QtWidgets.QFrame(self.homeModule)
        self.frameHomeContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHomeContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHomeContent.setObjectName("frameHomeContent")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frameHomeContent)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frameHome = QtWidgets.QFrame(self.frameHomeContent)
        self.frameHome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameHome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHome.setLineWidth(0)
        self.frameHome.setObjectName("frameHome")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frameHome)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frameBanner = QtWidgets.QFrame(self.frameHome)
        self.frameBanner.setMinimumSize(QtCore.QSize(800, 0))
        self.frameBanner.setStyleSheet("QFrame {\n"
"    background-color : #FFFFFF;\n"
"}")
        self.frameBanner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBanner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBanner.setObjectName("frameBanner")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frameBanner)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 0, 0, 1, 1)
        self.labelVersionProgram = QtWidgets.QLabel(self.frameBanner)
        self.labelVersionProgram.setStyleSheet("QLabel {\n"
"    font : 77 9pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #000000;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding-left: 10px;\n"
"    padding-bottom: 10px\n"
"}")
        self.labelVersionProgram.setObjectName("labelVersionProgram")
        self.gridLayout_15.addWidget(self.labelVersionProgram, 2, 1, 1, 1)
        self.labelBanner = QtWidgets.QLabel(self.frameBanner)
        self.labelBanner.setMinimumSize(QtCore.QSize(0, 0))
        self.labelBanner.setMaximumSize(QtCore.QSize(1000, 250))
        self.labelBanner.setText("")
        self.labelBanner.setPixmap(QtGui.QPixmap("app/resources/img/banners/banner-2.png"))
        self.labelBanner.setScaledContents(True)
        self.labelBanner.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBanner.setObjectName("labelBanner")
        self.gridLayout_15.addWidget(self.labelBanner, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 0, 2, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem5, 3, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frameBanner, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frameHome, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frameHomeContent, 1, 0, 1, 1)
        self.stackedWidgetModule.addWidget(self.homeModule)
        self.propertiesModule = QtWidgets.QWidget()
        self.propertiesModule.setObjectName("propertiesModule")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.propertiesModule)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.labelPropertiesModule = QtWidgets.QLabel(self.propertiesModule)
        self.labelPropertiesModule.setMinimumSize(QtCore.QSize(0, 50))
        self.labelPropertiesModule.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelPropertiesModule.setBaseSize(QtCore.QSize(0, 50))
        self.labelPropertiesModule.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelPropertiesModule.setObjectName("labelPropertiesModule")
        self.gridLayout_17.addWidget(self.labelPropertiesModule, 0, 0, 1, 1)
        self.framePropertiesContent = QtWidgets.QFrame(self.propertiesModule)
        self.framePropertiesContent.setStyleSheet("QFrame {\n"
"    background-color : #F0F0F0;\n"
"}")
        self.framePropertiesContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePropertiesContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePropertiesContent.setLineWidth(0)
        self.framePropertiesContent.setObjectName("framePropertiesContent")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.framePropertiesContent)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBoxProperties = QtWidgets.QGroupBox(self.framePropertiesContent)
        self.groupBoxProperties.setStyleSheet("QGroupBox {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.groupBoxProperties.setObjectName("groupBoxProperties")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBoxProperties)
        self.gridLayout_22.setContentsMargins(18, -1, 18, -1)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.lineEditSystem = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditSystem.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditSystem.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditSystem.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditSystem.setObjectName("lineEditSystem")
        self.gridLayout_22.addWidget(self.lineEditSystem, 5, 2, 1, 1)
        self.lineEditMachine = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditMachine.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditMachine.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditMachine.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditMachine.setObjectName("lineEditMachine")
        self.gridLayout_22.addWidget(self.lineEditMachine, 9, 2, 1, 1)
        self.labelArchitecture = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelArchitecture.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelArchitecture.setObjectName("labelArchitecture")
        self.gridLayout_22.addWidget(self.labelArchitecture, 10, 0, 1, 1)
        self.lineEditArchitecture = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditArchitecture.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditArchitecture.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditArchitecture.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditArchitecture.setObjectName("lineEditArchitecture")
        self.gridLayout_22.addWidget(self.lineEditArchitecture, 10, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBoxProperties)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_22.addWidget(self.line_2, 4, 2, 1, 1)
        self.labelSystem = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelSystem.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelSystem.setObjectName("labelSystem")
        self.gridLayout_22.addWidget(self.labelSystem, 5, 0, 1, 1)
        self.labelProcessor = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelProcessor.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelProcessor.setObjectName("labelProcessor")
        self.gridLayout_22.addWidget(self.labelProcessor, 7, 0, 1, 1)
        self.lineEditExecutionPath = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditExecutionPath.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditExecutionPath.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditExecutionPath.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditExecutionPath.setObjectName("lineEditExecutionPath")
        self.gridLayout_22.addWidget(self.lineEditExecutionPath, 2, 2, 1, 1)
        self.labelSystemVersion = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelSystemVersion.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelSystemVersion.setObjectName("labelSystemVersion")
        self.gridLayout_22.addWidget(self.labelSystemVersion, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBoxProperties)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_22.addWidget(self.line, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem6, 12, 0, 1, 3)
        self.labelMachine = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelMachine.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelMachine.setObjectName("labelMachine")
        self.gridLayout_22.addWidget(self.labelMachine, 9, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem7, 3, 0, 1, 3)
        self.labelTitleExecution = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelTitleExecution.setStyleSheet("QLabel {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.labelTitleExecution.setObjectName("labelTitleExecution")
        self.gridLayout_22.addWidget(self.labelTitleExecution, 1, 0, 1, 1)
        self.lineEditProcessor = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditProcessor.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditProcessor.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditProcessor.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditProcessor.setObjectName("lineEditProcessor")
        self.gridLayout_22.addWidget(self.lineEditProcessor, 7, 2, 1, 1)
        self.lineEditPlatform = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditPlatform.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditPlatform.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditPlatform.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditPlatform.setObjectName("lineEditPlatform")
        self.gridLayout_22.addWidget(self.lineEditPlatform, 11, 2, 1, 1)
        self.lineEditSystemVersion = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditSystemVersion.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditSystemVersion.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditSystemVersion.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditSystemVersion.setObjectName("lineEditSystemVersion")
        self.gridLayout_22.addWidget(self.lineEditSystemVersion, 6, 2, 1, 1)
        self.labelNode = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelNode.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelNode.setObjectName("labelNode")
        self.gridLayout_22.addWidget(self.labelNode, 8, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_22.addItem(spacerItem8, 0, 0, 1, 3)
        self.labelPlatform = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelPlatform.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelPlatform.setObjectName("labelPlatform")
        self.gridLayout_22.addWidget(self.labelPlatform, 11, 0, 1, 1)
        self.lineEditNode = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.lineEditNode.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditNode.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditNode.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditNode.setObjectName("lineEditNode")
        self.gridLayout_22.addWidget(self.lineEditNode, 8, 2, 1, 1)
        self.labeExecutionPath = QtWidgets.QLabel(self.groupBoxProperties)
        self.labeExecutionPath.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labeExecutionPath.setObjectName("labeExecutionPath")
        self.gridLayout_22.addWidget(self.labeExecutionPath, 2, 0, 1, 1)
        self.labelTitleSystem = QtWidgets.QLabel(self.groupBoxProperties)
        self.labelTitleSystem.setStyleSheet("QLabel {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.labelTitleSystem.setObjectName("labelTitleSystem")
        self.gridLayout_22.addWidget(self.labelTitleSystem, 4, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBoxProperties, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem9, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.framePropertiesContent, 1, 0, 1, 1)
        self.stackedWidgetModule.addWidget(self.propertiesModule)
        self.executionModule = QtWidgets.QWidget()
        self.executionModule.setObjectName("executionModule")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.executionModule)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frameExecutionContent = QtWidgets.QFrame(self.executionModule)
        self.frameExecutionContent.setStyleSheet("QFrame {\n"
"    background-color : #F0F0F0;\n"
"}")
        self.frameExecutionContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameExecutionContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameExecutionContent.setLineWidth(0)
        self.frameExecutionContent.setObjectName("frameExecutionContent")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frameExecutionContent)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.labelExecutionModule = QtWidgets.QLabel(self.frameExecutionContent)
        self.labelExecutionModule.setMinimumSize(QtCore.QSize(0, 50))
        self.labelExecutionModule.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelExecutionModule.setBaseSize(QtCore.QSize(0, 50))
        self.labelExecutionModule.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelExecutionModule.setObjectName("labelExecutionModule")
        self.gridLayout_24.addWidget(self.labelExecutionModule, 0, 0, 1, 2)
        self.treeViewFileSystem = QtWidgets.QTreeView(self.frameExecutionContent)
        self.treeViewFileSystem.setObjectName("treeViewFileSystem")
        self.gridLayout_24.addWidget(self.treeViewFileSystem, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_24.addItem(spacerItem10, 1, 0, 1, 2)
        self.groupBoxFile = QtWidgets.QGroupBox(self.frameExecutionContent)
        self.groupBoxFile.setStyleSheet("QGroupBox {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.groupBoxFile.setObjectName("groupBoxFile")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxFile)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButtonExecuteFileSelected = QtWidgets.QPushButton(self.groupBoxFile)
        self.pushButtonExecuteFileSelected.setStyleSheet("QPushButton{\n"
"    background-color : #D37242;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #BB673D;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExecuteFileSelected.setIcon(icon7)
        self.pushButtonExecuteFileSelected.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonExecuteFileSelected.setFlat(True)
        self.pushButtonExecuteFileSelected.setObjectName("pushButtonExecuteFileSelected")
        self.gridLayout_14.addWidget(self.pushButtonExecuteFileSelected, 3, 0, 1, 1)
        self.lineEditFileSelected = QtWidgets.QLineEdit(self.groupBoxFile)
        self.lineEditFileSelected.setMinimumSize(QtCore.QSize(500, 0))
        self.lineEditFileSelected.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEditFileSelected.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditFileSelected.setObjectName("lineEditFileSelected")
        self.gridLayout_14.addWidget(self.lineEditFileSelected, 1, 0, 1, 1)
        self.labelFileSelected = QtWidgets.QLabel(self.groupBoxFile)
        self.labelFileSelected.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelFileSelected.setObjectName("labelFileSelected")
        self.gridLayout_14.addWidget(self.labelFileSelected, 0, 0, 1, 1)
        self.pushButtonSelectFile = QtWidgets.QPushButton(self.groupBoxFile)
        self.pushButtonSelectFile.setStyleSheet("QPushButton{\n"
"    background-color : #6178B2;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #7D99E0;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelectFile.setIcon(icon8)
        self.pushButtonSelectFile.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSelectFile.setObjectName("pushButtonSelectFile")
        self.gridLayout_14.addWidget(self.pushButtonSelectFile, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem11, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem12, 4, 0, 1, 1)
        self.listViewFileHistory = QtWidgets.QListView(self.groupBoxFile)
        self.listViewFileHistory.setStyleSheet("QListView{\n"
"    background-color : #F0F0F0;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #D37242;\n"
"    border-radius : 0px;\n"
"    padding-left : 50px;\n"
"    text-align : left;\n"
"}")
        self.listViewFileHistory.setObjectName("listViewFileHistory")
        self.gridLayout_14.addWidget(self.listViewFileHistory, 5, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBoxFile, 2, 1, 1, 1)
        self.gridLayout_21.addWidget(self.frameExecutionContent, 0, 0, 1, 1)
        self.stackedWidgetModule.addWidget(self.executionModule)
        self.analysisModule = QtWidgets.QWidget()
        self.analysisModule.setStyleSheet("")
        self.analysisModule.setObjectName("analysisModule")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.analysisModule)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frameAnalysisContent = QtWidgets.QFrame(self.analysisModule)
        self.frameAnalysisContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAnalysisContent.setLineWidth(0)
        self.frameAnalysisContent.setObjectName("frameAnalysisContent")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frameAnalysisContent)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frameSearcher = QtWidgets.QFrame(self.frameAnalysisContent)
        self.frameSearcher.setMinimumSize(QtCore.QSize(50, 80))
        self.frameSearcher.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frameSearcher.setStyleSheet("QFrame {\n"
"    background-color : #222222;\n"
"}")
        self.frameSearcher.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameSearcher.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameSearcher.setLineWidth(0)
        self.frameSearcher.setObjectName("frameSearcher")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frameSearcher)
        self.gridLayout_9.setContentsMargins(0, 0, 9, 9)
        self.gridLayout_9.setSpacing(9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEditSearcher = QtWidgets.QLineEdit(self.frameSearcher)
        self.lineEditSearcher.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditSearcher.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lineEditSearcher.setStyleSheet("QLineEdit{\n"
"    background-color: #FFFFFF;\n"
"    font : 72 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #111111;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"}\n"
"")
        self.lineEditSearcher.setObjectName("lineEditSearcher")
        self.gridLayout_9.addWidget(self.lineEditSearcher, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem13, 0, 1, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem14, 2, 1, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 1, 0, 1, 1)
        self.pushButtonSearch = QtWidgets.QPushButton(self.frameSearcher)
        self.pushButtonSearch.setMinimumSize(QtCore.QSize(170, 30))
        self.pushButtonSearch.setMaximumSize(QtCore.QSize(70, 30))
        self.pushButtonSearch.setStyleSheet("QPushButton{\n"
"    background-color: #D37242;\n"
"\n"
"    border-top-left-radius: 14px;\n"
"    border-bottom-left-radius: 14px;\n"
"    border-top-right-radius: 14px;\n"
"    border-bottom-right-radius: 14px;\n"
"\n"
"    font : 75 10pt \"Microsoft JhengHei UI\" bold;\n"
"    color: #FFFFFF;\n"
"    padding : 10px;\n"
"\n"
"    text-align : left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #BB673D;\n"
"    border-top-left-radius: 14px;    \n"
"    border-bottom-left-radius: 14px;\n"
"    border-top-right-radius: 14px;\n"
"    border-bottom-right-radius: 14px;\n"
"\n"
"    font : 75 10pt \"Microsoft JhengHei UI\" bold;\n"
"    color: #FFFFFF;\n"
"    text-align : left;\n"
"\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-arrow-circle-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSearch.setIcon(icon9)
        self.pushButtonSearch.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.gridLayout_9.addWidget(self.pushButtonSearch, 1, 2, 1, 1)
        self.gridLayout_10.addWidget(self.frameSearcher, 1, 0, 1, 2)
        self.labelAnalysisModule = QtWidgets.QLabel(self.frameAnalysisContent)
        self.labelAnalysisModule.setMinimumSize(QtCore.QSize(0, 50))
        self.labelAnalysisModule.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelAnalysisModule.setBaseSize(QtCore.QSize(0, 50))
        self.labelAnalysisModule.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelAnalysisModule.setLineWidth(0)
        self.labelAnalysisModule.setObjectName("labelAnalysisModule")
        self.gridLayout_10.addWidget(self.labelAnalysisModule, 0, 0, 1, 2)
        self.frameAnalysis = QtWidgets.QFrame(self.frameAnalysisContent)
        self.frameAnalysis.setStyleSheet("QFrame{\n"
"    background-color: #F0F0F0;\n"
"    border-radius : 0px;\n"
"}\n"
"")
        self.frameAnalysis.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameAnalysis.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAnalysis.setLineWidth(0)
        self.frameAnalysis.setObjectName("frameAnalysis")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frameAnalysis)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setHorizontalSpacing(0)
        self.gridLayout_12.setVerticalSpacing(9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frameAnalysisPanel = QtWidgets.QFrame(self.frameAnalysis)
        self.frameAnalysisPanel.setMinimumSize(QtCore.QSize(46, 0))
        self.frameAnalysisPanel.setMaximumSize(QtCore.QSize(46, 16777215))
        self.frameAnalysisPanel.setStyleSheet("QFrame {\n"
"    background-color : #6B5876;\n"
"}")
        self.frameAnalysisPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameAnalysisPanel.setLineWidth(0)
        self.frameAnalysisPanel.setObjectName("frameAnalysisPanel")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frameAnalysisPanel)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem16, 1, 0, 1, 1)
        self.pushButtonCreateProduct = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonCreateProduct.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateProduct.setIcon(icon10)
        self.pushButtonCreateProduct.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCreateProduct.setObjectName("pushButtonCreateProduct")
        self.gridLayout_8.addWidget(self.pushButtonCreateProduct, 5, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem17, 2, 0, 1, 1)
        self.pushButtonDeleteData = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonDeleteData.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDeleteData.setIcon(icon11)
        self.pushButtonDeleteData.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDeleteData.setObjectName("pushButtonDeleteData")
        self.gridLayout_8.addWidget(self.pushButtonDeleteData, 9, 0, 1, 1)
        self.pushButtonRequestData = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonRequestData.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-view-column.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRequestData.setIcon(icon12)
        self.pushButtonRequestData.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonRequestData.setObjectName("pushButtonRequestData")
        self.gridLayout_8.addWidget(self.pushButtonRequestData, 3, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem18, 10, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem19, 12, 0, 1, 1)
        self.pushButtonExportData = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonExportData.setMinimumSize(QtCore.QSize(44, 42))
        self.pushButtonExportData.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButtonExportData.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExportData.setIcon(icon13)
        self.pushButtonExportData.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonExportData.setFlat(True)
        self.pushButtonExportData.setObjectName("pushButtonExportData")
        self.gridLayout_8.addWidget(self.pushButtonExportData, 11, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem20, 4, 0, 1, 1)
        self.pushButtonCreateTransport = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonCreateTransport.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-truck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateTransport.setIcon(icon14)
        self.pushButtonCreateTransport.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCreateTransport.setFlat(True)
        self.pushButtonCreateTransport.setObjectName("pushButtonCreateTransport")
        self.gridLayout_8.addWidget(self.pushButtonCreateTransport, 6, 0, 1, 1)
        self.pushButtonCreateContract = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonCreateContract.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-description.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateContract.setIcon(icon15)
        self.pushButtonCreateContract.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCreateContract.setObjectName("pushButtonCreateContract")
        self.gridLayout_8.addWidget(self.pushButtonCreateContract, 7, 0, 1, 1)
        self.pushButtonSwipePanelAnalysis = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonSwipePanelAnalysis.setEnabled(True)
        self.pushButtonSwipePanelAnalysis.setMinimumSize(QtCore.QSize(44, 42))
        self.pushButtonSwipePanelAnalysis.setBaseSize(QtCore.QSize(0, 0))
        self.pushButtonSwipePanelAnalysis.setStyleSheet("QPushButton{\n"
"    background-color: #D37242;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #AD5B32;\n"
"}\n"
"")
        self.pushButtonSwipePanelAnalysis.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSwipePanelAnalysis.setIcon(icon16)
        self.pushButtonSwipePanelAnalysis.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSwipePanelAnalysis.setFlat(True)
        self.pushButtonSwipePanelAnalysis.setObjectName("pushButtonSwipePanelAnalysis")
        self.gridLayout_8.addWidget(self.pushButtonSwipePanelAnalysis, 0, 0, 1, 1)
        self.pushButtonCreateInternationalContract = QtWidgets.QPushButton(self.frameAnalysisPanel)
        self.pushButtonCreateInternationalContract.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-right : 5px solid #D37242;\n"
"}\n"
"\n"
"")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateInternationalContract.setIcon(icon17)
        self.pushButtonCreateInternationalContract.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCreateInternationalContract.setFlat(True)
        self.pushButtonCreateInternationalContract.setObjectName("pushButtonCreateInternationalContract")
        self.gridLayout_8.addWidget(self.pushButtonCreateInternationalContract, 8, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frameAnalysisPanel, 0, 1, 1, 1)
        self.frameAnalysisView = QtWidgets.QFrame(self.frameAnalysis)
        self.frameAnalysisView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameAnalysisView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAnalysisView.setLineWidth(0)
        self.frameAnalysisView.setObjectName("frameAnalysisView")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frameAnalysisView)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frameData = QtWidgets.QFrame(self.frameAnalysisView)
        self.frameData.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameData.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameData.setLineWidth(0)
        self.frameData.setObjectName("frameData")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frameData)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.listViewTables = QtWidgets.QListView(self.frameData)
        self.listViewTables.setMaximumSize(QtCore.QSize(500, 16777215))
        self.listViewTables.setStyleSheet("QListView {\n"
"    background-color : #F0F0F0;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #D37242;\n"
"    border-radius : 0px;\n"
"    padding-left : 50px;\n"
"    text-align : left;\n"
"}\n"
"\n"
"QListView::hover {\n"
"    color : #6B5876;\n"
"}")
        self.listViewTables.setObjectName("listViewTables")
        self.gridLayout_16.addWidget(self.listViewTables, 0, 0, 1, 1)
        self.tableWidgetAnalysis = QtWidgets.QTableWidget(self.frameData)
        self.tableWidgetAnalysis.setStyleSheet("QTableView {\n"
"    background-color : #F0F0F0;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #D37242;\n"
"    border-radius : 0px;\n"
"    padding-left : 50px;\n"
"    text-align : left;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color : #6178B2;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"}")
        self.tableWidgetAnalysis.setObjectName("tableWidgetAnalysis")
        self.tableWidgetAnalysis.setColumnCount(0)
        self.tableWidgetAnalysis.setRowCount(0)
        self.gridLayout_16.addWidget(self.tableWidgetAnalysis, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frameData, 5, 0, 1, 2)
        self.frameSeparator = QtWidgets.QFrame(self.frameAnalysisView)
        self.frameSeparator.setMinimumSize(QtCore.QSize(0, 40))
        self.frameSeparator.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frameSeparator.setStyleSheet("QFrame {\n"
"    background : #DDDDDD;\n"
"}")
        self.frameSeparator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeparator.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameSeparator.setLineWidth(0)
        self.frameSeparator.setObjectName("frameSeparator")
        self.gridLayout_13.addWidget(self.frameSeparator, 3, 0, 1, 2)
        self.gridLayout_12.addWidget(self.frameAnalysisView, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frameAnalysis, 2, 0, 1, 2)
        self.gridLayout_11.addWidget(self.frameAnalysisContent, 0, 0, 1, 1)
        self.stackedWidgetModule.addWidget(self.analysisModule)
        self.gridLayout_6.addWidget(self.stackedWidgetModule, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameContainer, 1, 1, 1, 1)
        self.frameWindowPanel = QtWidgets.QFrame(self.centralWidget)
        self.frameWindowPanel.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frameWindowPanel.setStyleSheet("QFrame {\n"
"    background : #000000\n"
"}")
        self.frameWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameWindowPanel.setLineWidth(0)
        self.frameWindowPanel.setObjectName("frameWindowPanel")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameWindowPanel)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.framePushButtonWindowPanel = QtWidgets.QFrame(self.frameWindowPanel)
        self.framePushButtonWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePushButtonWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePushButtonWindowPanel.setLineWidth(0)
        self.framePushButtonWindowPanel.setObjectName("framePushButtonWindowPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.framePushButtonWindowPanel)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonClose = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setStyleSheet("QPushButton {\n"
"    background-color : #A93226;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color : #87281E\n"
"}")
        self.pushButtonClose.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon18)
        self.pushButtonClose.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_4.addWidget(self.pushButtonClose, 0, 2, 1, 1)
        self.pushButtonRestore = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonRestore.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        self.pushButtonRestore.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRestore.setIcon(icon19)
        self.pushButtonRestore.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.gridLayout_4.addWidget(self.pushButtonRestore, 0, 1, 1, 1)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        self.pushButtonMinimize.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("app/resources/img/icons/24x24/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMinimize.setIcon(icon20)
        self.pushButtonMinimize.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.gridLayout_4.addWidget(self.pushButtonMinimize, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.framePushButtonWindowPanel, 0, 2, 1, 1)
        self.labelWindowTitle = QtWidgets.QLabel(self.frameWindowPanel)
        self.labelWindowTitle.setStyleSheet("QLabel {\n"
"    font : 77 15pt \"Microsoft JhengHei UI\";\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color : #4F6FA0;\n"
"}\n"
"")
        self.labelWindowTitle.setText("")
        self.labelWindowTitle.setObjectName("labelWindowTitle")
        self.gridLayout_5.addWidget(self.labelWindowTitle, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frameWindowPanel, 0, 0, 1, 2)
        self.setCentralWidget(self.centralWidget)

        self.retranslateUi()
        self.stackedWidgetModule.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonLeaveSession.setText(_translate("MainWindow", "Cerrar sesion"))
        self.pushButtonAnalysisModule.setText(_translate("MainWindow", "Analisis"))
        self.pushButtonPropertiesModule.setText(_translate("MainWindow", "Propiedades"))
        self.pushButtonHomeModule.setText(_translate("MainWindow", "Inicio"))
        self.pushButtonExecutionModule.setText(_translate("MainWindow", "Ejecucion"))
        self.pushButtonOpenWebsite.setText(_translate("MainWindow", "Ir al Sistema Web"))
        self.labelHomeModule.setText(_translate("MainWindow", "Inicio"))
        self.labelVersionProgram.setText(_translate("MainWindow", "version 1.0"))
        self.labelPropertiesModule.setText(_translate("MainWindow", "Propiedades"))
        self.groupBoxProperties.setTitle(_translate("MainWindow", "Feria Virtual Maipo Grande - Entorno"))
        self.labelArchitecture.setText(_translate("MainWindow", "Arquitectura"))
        self.labelSystem.setText(_translate("MainWindow", "Sistema"))
        self.labelProcessor.setText(_translate("MainWindow", "Procesador"))
        self.labelSystemVersion.setText(_translate("MainWindow", "Version"))
        self.labelMachine.setText(_translate("MainWindow", "Maquina"))
        self.labelTitleExecution.setText(_translate("MainWindow", "Ejecución"))
        self.labelNode.setText(_translate("MainWindow", "Nodo"))
        self.labelPlatform.setText(_translate("MainWindow", "Plataforma"))
        self.labeExecutionPath.setText(_translate("MainWindow", "Ruta de ejecución"))
        self.labelTitleSystem.setText(_translate("MainWindow", "Sistema"))
        self.labelExecutionModule.setText(_translate("MainWindow", "Ejecucion"))
        self.groupBoxFile.setTitle(_translate("MainWindow", "Ejecutor"))
        self.pushButtonExecuteFileSelected.setText(_translate("MainWindow", "Ejecutar archivo"))
        self.labelFileSelected.setText(_translate("MainWindow", "Archivo seleccionado"))
        self.pushButtonSelectFile.setText(_translate("MainWindow", "Seleccionar archivo"))
        self.pushButtonSearch.setText(_translate("MainWindow", "Buscar"))
        self.labelAnalysisModule.setText(_translate("MainWindow", "Analisis"))
        self.pushButtonCreateProduct.setText(_translate("MainWindow", "Publicar subasta"))
        self.pushButtonDeleteData.setText(_translate("MainWindow", "Eliminar dato"))
        self.pushButtonRequestData.setText(_translate("MainWindow", "Listar API"))
        self.pushButtonExportData.setText(_translate("MainWindow", "Exportar datos solicitados"))
        self.pushButtonCreateTransport.setText(_translate("MainWindow", "Publicar transporte"))
        self.pushButtonCreateContract.setText(_translate("MainWindow", "Publicar contrato"))
        self.pushButtonCreateInternationalContract.setText(_translate("MainWindow", "Publicar contrato internacional"))
