# Generated by Django 4.1.2 on 2022-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maipogrande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default='2022-11-01 06:32:29'),
        ),
    ]
