# Generated by Django 4.1.2 on 2022-11-02 04:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maipogrande', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default='2022-11-02 01:31:13'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default='2022-11-02 01:31:13')),
                ('image', models.ImageField(null=True, upload_to='media/post/')),
                ('type', models.CharField(blank=True, choices=[('AVION', 'AVION'), ('AVIONETA', 'AVIONETA'), ('HELICOPTERO', 'HELICOPTERO'), ('BARCO', 'BARCO'), ('LANCHA', 'LANCHA'), ('CAMIONETA', 'CAMIONETA'), ('CAMION', 'CAMION'), ('AUTO', 'AUTO')], default='CAMION', max_length=30)),
                ('patent', models.CharField(blank=True, max_length=300)),
                ('size', models.CharField(blank=True, max_length=300)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('refrigeration', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp', 'type'],
            },
        ),
    ]
