# Generated by Django 4.1.2 on 2022-11-02 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maipogrande', '0003_alter_post_timestamp_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default='2022-11-02 02:26:36'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='timestamp',
            field=models.DateTimeField(default='2022-11-02 02:26:36'),
        ),
    ]
