# Generated by Django 4.1 on 2022-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maipogrande', '0003_alter_contact_email_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='id_request',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
