# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publish_transport.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 521)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frameWindowPanel = QtWidgets.QFrame(self.centralWidget)
        self.frameWindowPanel.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frameWindowPanel.setStyleSheet("QFrame {\n"
"    background : #000000\n"
"}")
        self.frameWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameWindowPanel.setLineWidth(0)
        self.frameWindowPanel.setObjectName("frameWindowPanel")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameWindowPanel)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.framePushButtonWindowPanel = QtWidgets.QFrame(self.frameWindowPanel)
        self.framePushButtonWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePushButtonWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePushButtonWindowPanel.setLineWidth(0)
        self.framePushButtonWindowPanel.setObjectName("framePushButtonWindowPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.framePushButtonWindowPanel)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonClose = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setStyleSheet("QPushButton {\n"
"    background-color : #A93226;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color : #87281E\n"
"}")
        self.pushButtonClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PySide6/project/resources/img/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon)
        self.pushButtonClose.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_4.addWidget(self.pushButtonClose, 0, 2, 1, 1)
        self.pushButtonRestore = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonRestore.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        self.pushButtonRestore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("PySide6/project/resources/img/icons/24x24/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRestore.setIcon(icon1)
        self.pushButtonRestore.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.gridLayout_4.addWidget(self.pushButtonRestore, 0, 1, 1, 1)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        self.pushButtonMinimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("PySide6/project/resources/img/icons/24x24/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMinimize.setIcon(icon2)
        self.pushButtonMinimize.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.gridLayout_4.addWidget(self.pushButtonMinimize, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.framePushButtonWindowPanel, 0, 2, 1, 1)
        self.labelWindowTitle = QtWidgets.QLabel(self.frameWindowPanel)
        self.labelWindowTitle.setStyleSheet("QLabel {\n"
"    font : 77 15pt \"Microsoft JhengHei UI\";\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color : #4F6FA0;\n"
"}\n"
"")
        self.labelWindowTitle.setText("")
        self.labelWindowTitle.setObjectName("labelWindowTitle")
        self.gridLayout_5.addWidget(self.labelWindowTitle, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frameWindowPanel, 0, 0, 1, 2)
        self.frameContainer = QtWidgets.QFrame(self.centralWidget)
        self.frameContainer.setStyleSheet("QFrame {\n"
"    background : #FFFFFF;\n"
"}")
        self.frameContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameContainer.setLineWidth(0)
        self.frameContainer.setObjectName("frameContainer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frameContainer)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelForm = QtWidgets.QLabel(self.frameContainer)
        self.labelForm.setMinimumSize(QtCore.QSize(0, 50))
        self.labelForm.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelForm.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelForm.setObjectName("labelForm")
        self.gridLayout_6.addWidget(self.labelForm, 0, 0, 1, 1)
        self.framePostForm = QtWidgets.QFrame(self.frameContainer)
        self.framePostForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePostForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePostForm.setObjectName("framePostForm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.framePostForm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBoxForm = QtWidgets.QGroupBox(self.framePostForm)
        self.groupBoxForm.setStyleSheet("QGroupBox {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.groupBoxForm.setTitle("")
        self.groupBoxForm.setObjectName("groupBoxForm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPatent = QtWidgets.QLabel(self.groupBoxForm)
        self.labelPatent.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelPatent.setObjectName("labelPatent")
        self.gridLayout_2.addWidget(self.labelPatent, 1, 0, 1, 1)
        self.lineEditPatent = QtWidgets.QLineEdit(self.groupBoxForm)
        self.lineEditPatent.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditPatent.setObjectName("lineEditPatent")
        self.gridLayout_2.addWidget(self.lineEditPatent, 1, 2, 1, 1)
        self.pushButtonSelectImage = QtWidgets.QPushButton(self.groupBoxForm)
        self.pushButtonSelectImage.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButtonSelectImage.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButtonSelectImage.setStyleSheet("QPushButton{\n"
"    background-color : #6B5876;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #836C90;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"\n"
"")
        self.pushButtonSelectImage.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/icons/24x24/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelectImage.setIcon(icon3)
        self.pushButtonSelectImage.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSelectImage.setFlat(True)
        self.pushButtonSelectImage.setObjectName("pushButtonSelectImage")
        self.gridLayout_2.addWidget(self.pushButtonSelectImage, 2, 3, 1, 1)
        self.comboBoxRefrigeration = QtWidgets.QComboBox(self.groupBoxForm)
        self.comboBoxRefrigeration.setStyleSheet("QComboBox {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.comboBoxRefrigeration.setObjectName("comboBoxRefrigeration")
        self.comboBoxRefrigeration.addItem("")
        self.comboBoxRefrigeration.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxRefrigeration, 5, 2, 1, 1)
        self.labelSize = QtWidgets.QLabel(self.groupBoxForm)
        self.labelSize.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelSize.setObjectName("labelSize")
        self.gridLayout_2.addWidget(self.labelSize, 3, 0, 1, 1)
        self.labelCapacity = QtWidgets.QLabel(self.groupBoxForm)
        self.labelCapacity.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelCapacity.setObjectName("labelCapacity")
        self.gridLayout_2.addWidget(self.labelCapacity, 4, 0, 1, 1)
        self.lineEditSize = QtWidgets.QLineEdit(self.groupBoxForm)
        self.lineEditSize.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditSize.setObjectName("lineEditSize")
        self.gridLayout_2.addWidget(self.lineEditSize, 3, 2, 1, 1)
        self.labelRefrigeration = QtWidgets.QLabel(self.groupBoxForm)
        self.labelRefrigeration.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelRefrigeration.setObjectName("labelRefrigeration")
        self.gridLayout_2.addWidget(self.labelRefrigeration, 5, 0, 1, 1)
        self.lineEditImageFilePath = QtWidgets.QLineEdit(self.groupBoxForm)
        self.lineEditImageFilePath.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditImageFilePath.setObjectName("lineEditImageFilePath")
        self.gridLayout_2.addWidget(self.lineEditImageFilePath, 2, 2, 1, 1)
        self.labelType = QtWidgets.QLabel(self.groupBoxForm)
        self.labelType.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelType.setObjectName("labelType")
        self.gridLayout_2.addWidget(self.labelType, 0, 0, 1, 1)
        self.labelImage = QtWidgets.QLabel(self.groupBoxForm)
        self.labelImage.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelImage.setObjectName("labelImage")
        self.gridLayout_2.addWidget(self.labelImage, 2, 0, 1, 1)
        self.comboBoxType = QtWidgets.QComboBox(self.groupBoxForm)
        self.comboBoxType.setStyleSheet("QComboBox {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxType, 0, 2, 1, 1)
        self.pushButtonPost = QtWidgets.QPushButton(self.groupBoxForm)
        self.pushButtonPost.setMinimumSize(QtCore.QSize(250, 0))
        self.pushButtonPost.setStyleSheet("QPushButton{\n"
"    background-color : #D37242;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #BB673D;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/icons/24x24/cil-paper-plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPost.setIcon(icon4)
        self.pushButtonPost.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonPost.setObjectName("pushButtonPost")
        self.gridLayout_2.addWidget(self.pushButtonPost, 7, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 2, 1, 1)
        self.spinBoxCapacity = QtWidgets.QSpinBox(self.groupBoxForm)
        self.spinBoxCapacity.setStyleSheet("QSpinBox {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.spinBoxCapacity.setMinimum(1)
        self.spinBoxCapacity.setMaximum(1000)
        self.spinBoxCapacity.setObjectName("spinBoxCapacity")
        self.gridLayout_2.addWidget(self.spinBoxCapacity, 4, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxForm, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.framePostForm, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameContainer, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelForm.setText(_translate("MainWindow", "Crear una nueva publicación"))
        self.labelPatent.setText(_translate("MainWindow", "Patente"))
        self.comboBoxRefrigeration.setItemText(0, _translate("MainWindow", "SI"))
        self.comboBoxRefrigeration.setItemText(1, _translate("MainWindow", "NO"))
        self.labelSize.setText(_translate("MainWindow", "Tamaño"))
        self.labelCapacity.setText(_translate("MainWindow", "Capacidad"))
        self.labelRefrigeration.setText(_translate("MainWindow", "Refrigeracion"))
        self.labelType.setText(_translate("MainWindow", "Tipo de transporte"))
        self.labelImage.setText(_translate("MainWindow", "Imagen"))
        self.comboBoxType.setItemText(0, _translate("MainWindow", "CAMION"))
        self.comboBoxType.setItemText(1, _translate("MainWindow", "CAMIONETA"))
        self.comboBoxType.setItemText(2, _translate("MainWindow", "AUTO"))
        self.comboBoxType.setItemText(3, _translate("MainWindow", "AVION"))
        self.comboBoxType.setItemText(4, _translate("MainWindow", "AVIONETA"))
        self.comboBoxType.setItemText(5, _translate("MainWindow", "HELICOPTERO"))
        self.comboBoxType.setItemText(6, _translate("MainWindow", "BARCO"))
        self.comboBoxType.setItemText(7, _translate("MainWindow", "LANCHA"))
        self.pushButtonPost.setText(_translate("MainWindow", "Publicar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
